addSbtPlugin("com.typesafe.sbt" %% "sbt-native-packager" % "1.3.2")
addSbtPlugin("com.github.gseitz" % "sbt-release"         % "1.0.6")
//addSbtPlugin("com.codecommit"    % "sbt-github-packages" % "0.5.3")
addSbtPlugin("org.wartremover"   % "sbt-wartremover"     % "3.0.7")
addSbtPlugin("org.scalameta"     % "sbt-scalafmt"        % "2.4.6")
addSbtPlugin("ch.epfl.scala"     % "sbt-scalafix"        % "0.10.4")