name: Build & Test a Scala app

on:
  push:
    branches-ignore:
      - 'main'
      - 'release-*'
  workflow_call:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: 17
          apps:
      - run: sbt lintCheck
      - run: sbt compile
      - run: sbt test