name: Release libs

on:
  push:
    branches:
      - 'main'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-test:
    uses: ./.github/workflows/build.yml
  release-libs:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v3
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: 17
          apps:
      - run: sbt publish
